run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - revive
    - gofmt
    - goimports
    - misspell
    - goconst
    - typecheck
    - dupl
    - unconvert
  disable:
    - depguard

linters-settings:
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/mikecbrant/verified-permissions-authorizer
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: var-naming
        arguments: [["ID", "URL", "JSON"]]
      - name: receiver-naming
      - name: errorf
      - name: if-return
      - name: increment-decrement
      - name: superfluous-else
      - name: time-naming
      - name: unreachable-code
      - name: unused-parameter
  dupl:
    threshold: 200

issues:
  exclude-use-default: false
  exclude:
    - "error return value not checked.*(Close|Write|Fprint|Fprintln|Fprintf)"
  max-issues-per-linter: 0
  max-same-issues: 0
