$schema: https://json.schemastore.org/prettierrc
printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: 'all'
bracketSpacing: true
arrowParens: 'always'
endOfLine: 'lf'
