export default {
  $schema: 'https://json.schemastore.org/tsconfig',
  compilerOptions: {
    target: 'ES2023',
    module: 'ES2022',
    moduleResolution: 'Bundler',
    strict: true,
    forceConsistentCasingInFileNames: true,
    declaration: true,
    declarationMap: false,
    emitDeclarationOnly: false,
    esModuleInterop: true,
    skipLibCheck: false,
    sourceMap: false,
    outDir: 'dist',
    rootDir: 'src',
    noUncheckedIndexedAccess: true,
    noImplicitOverride: true,
    exactOptionalPropertyTypes: true,
    lib: ['ES2023'],
    types: ['node', 'aws-lambda'],
  },
  include: ['src'],
  exclude: ['**/*.test.ts', '**/*.spec.ts', 'dist', 'node_modules'],
}
