name: Publish Lambda Authorizer to npm

on:
  push:
    tags:
      - 'lambda-v*'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck + Lint (lambda)
        run: |
          pnpm --filter verified-permissions-lambda-authorizer typecheck
          pnpm --filter verified-permissions-lambda-authorizer lint

      - name: Build (lambda)
        run: pnpm --filter verified-permissions-lambda-authorizer build

      - name: Publish to npm (lambda)
        working-directory: packages/lambda-authorizer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public
