name: Release provider (publish to Pulumi Registry and npm)

on:
  push:
    tags:
      - 'provider-v*'
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.15.0

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck + Lint
        run: |
          pnpm -r typecheck
          pnpm -r lint

      - name: Build packages
        run: pnpm -r build

      - name: Publish Node SDK (provider) to npm
        working-directory: packages/provider
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public

      - name: Authenticate to Pulumi (for Registry publishing)
        uses: pulumi/auth-actions@v1
        with:
          # For public registry publishing, an access token is required.
          access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Publish package to Pulumi Registry
        run: |
          # Publish the component package to the public Pulumi Registry using the local schema.
          # Requires `PULUMI_ACCESS_TOKEN` and appropriate permissions for the publisher.
          npx pulumi@latest package publish packages/provider/schema.json --readme packages/provider/README.md
